ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_led_flash.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_trigger.o
#2015-5-19 longxiaowu@camera delete start for reason
#obj-$(CONFIG_MSMB_CAMERA) += msm_led_i2c_trigger.o
#obj-$(CONFIG_MSMB_CAMERA) += adp1660.o
#2015-5-19 longxiaowu@camera delete end
obj-$(CONFIG_MSMB_CAMERA) += msm_led_torch.o
obj-$(CONFIG_MSMB_CAMERA) += msm_flash.o

