#
# Makefile for nfc devices

# 15 Oct 2013, Yuyi <oppo@Independent Group>
# Rewritten to use pn544 driver.

obj-$(CONFIG_OPPO_MSM_FIND7)		+= pn544.o
obj-$(CONFIG_NFC_DEVICES)			+= pn544_op.o
obj-$(CONFIG_NFC_DEVICES)			+= p61_op.o
obj-$(CONFIG_OPPO_MSM_14021)		+= pn544_op.o
obj-$(CONFIG_OPPO_MSM_14021)		+= p61_n3.o
obj-$(CONFIG_OPPO_MSM_FIND7WX)		+= pn544.o
#obj-$(CONFIG_NFC_PN533)		+= pn533.o
#obj-$(CONFIG_NFC_WILINK)	+= nfcwilink.o

#ccflags-$(CONFIG_NFC_DEBUG) := -DDEBUG
